name: Build and Publish
on:
   push:
     branches:
       - master
       - develop
   workflow_dispatch:

permissions:
    contents: write
    packages: write

jobs:
  build:
   uses: mikopbx/.github-workflows/.github/workflows/extension-publish.yml@master
   with:
      initial_version: "1.50"
   permissions:
      contents: write
      packages: write
   secrets: inherit